name: Run Weekly Workflows
on:
  schedule:
    # Every week
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  supabase-keep-alive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.3.3"
      - run: bun install
      - run: bun run ./supabase/keep-alive.ts
        env:
          SUPABASE_PROD_URL: ${{ secrets.SUPABASE_PROD_URL }}
          SUPABASE_PROD_KEY: ${{ secrets.SUPABASE_PROD_KEY }}
          SUPABASE_STAGE_URL: ${{ secrets.SUPABASE_STAGE_URL }}
          SUPABASE_STAGE_KEY: ${{ secrets.SUPABASE_STAGE_KEY }}
